### ISSUE TITLE
Obtaining trained models for external use

### ISSUE THREAD

**Issue by Optimusik** [vandrw/lostpaw-transformer#2]
I tried to run your application and I succeeded with the help of another programmer and small changes in the configuration files I'm interested in this project because I'm a volunteer in Ukraine and it's hard for me to see a lot of ads in Facebook groups in Viber and Telegram chats about lost animals and sometimes it's completely impossible even for the owner to find his animal among all these hundreds of chats and thousands of messages. Because there are so many lost and found animals and my dream is to unite all these lost found animals somewhere in one place. So I'm interested in your project and I'd like to inquire. In addition to having a demo version of this page, have you ever tried running it for all to see? That is, to open a special site so that it is fully functional and thus help in the search for lost animals. Also me your work is interesting because it uses artificial intelligence. Because before we didn’t have it in the world literally in the last year it started to develop very strongly and with the help of artificial intelligence I hope that more animals will be able to find their former home. Because for animal recognition this is much more convenient than people just going through thousands of photos on their own looking for their lost friend. I asked the programmer who helped me launch your project about how much it would cost him to write or add something that is currently missing in the project to write a website to connect to the database and he answered me that it would cost perhaps around 1.000 dollars work (rewrite on python and add ai model to learn on pets pictures). So I was wondering if you have some option already ready in order not to pay so much money just to start working with it or vice versa you would not like to let it into the public domain just let's say So you did the experiment and ended up there?

**Comment by vandrw** [comment]
Hi @Optimusik ! We can provide you with the checkpoint files for the best model, so that you do not have to obtain the data again to train the model. We will send it shortly via the email address you have used to contact my colleague. You can then fine-tune it with more data if you wish, which can be achieved by providing `run_name` in the config file you're using (see `lostpaw/configs/container.yaml` in the repo). Furthermore, make sure that the `model_path` leads to the location where your model is stored. You can then run `scripts/train.py` again to continue training.

We currently do not have anything else for this project. We would have loved to have more, but had to stop due to time constraints. To use the model in another application, you will have to see our code with the Rust backend (see both `ml.py` and `ml.rs` in `webapp/backend/src`). This part of the code creates an encoding, which you can then compare with other encodings of pet images. However, the way we've built it right now is not scalable, and you'll need a vector database. PostgreSQL or Pinecone support this, so you could attempt to look into their similarity search function. Due to it being a demo, our current code simply loads images from a folder, encodes them and then stores them in RAM for comparison. Each new image would be compared against all other images already loaded in RAM. This would be very slow for a real world application, which is why we recommend obtaining the encoding of each uploaded image and then storing it directly to a vector database for further comparisons. Scraping all the apps you have suggested will also require additional work, unless everyone reports their lost pets in your app.

With everything said, a lot of work needs to be done to have a functional app. The code is licensed under the MIT licence, so you are free to pursue this idea if you wish. We are not currently available at the moment to work on such a project, but we believe that some NGOs in Western Europe would be interested in funding some money. We can get back to you on this at another date, but feel free to send some emails yourself if you know people!
